# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cloud_storage_pb2 as cloud__storage__pb2


class NodeManagementStub(object):
    """Node registration and management service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/cloud_storage.NodeManagement/RegisterNode',
                request_serializer=cloud__storage__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.RegisterNodeResponse.FromString,
                )
        self.SendHeartbeat = channel.unary_unary(
                '/cloud_storage.NodeManagement/SendHeartbeat',
                request_serializer=cloud__storage__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.HeartbeatResponse.FromString,
                )
        self.NotifyActive = channel.unary_unary(
                '/cloud_storage.NodeManagement/NotifyActive',
                request_serializer=cloud__storage__pb2.ActiveNotificationRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.ActiveNotificationResponse.FromString,
                )
        self.GetNodeInfo = channel.unary_unary(
                '/cloud_storage.NodeManagement/GetNodeInfo',
                request_serializer=cloud__storage__pb2.NodeInfoRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.NodeInfoResponse.FromString,
                )


class NodeManagementServicer(object):
    """Node registration and management service
    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyActive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=cloud__storage__pb2.RegisterNodeRequest.FromString,
                    response_serializer=cloud__storage__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=cloud__storage__pb2.HeartbeatRequest.FromString,
                    response_serializer=cloud__storage__pb2.HeartbeatResponse.SerializeToString,
            ),
            'NotifyActive': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyActive,
                    request_deserializer=cloud__storage__pb2.ActiveNotificationRequest.FromString,
                    response_serializer=cloud__storage__pb2.ActiveNotificationResponse.SerializeToString,
            ),
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=cloud__storage__pb2.NodeInfoRequest.FromString,
                    response_serializer=cloud__storage__pb2.NodeInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud_storage.NodeManagement', rpc_method_handlers)
    server.add_generic_handler(generic_handler)


 # This class is part of an EXPERIMENTAL API.
class NodeManagement(object):
    """Node registration and management service
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.NodeManagement/RegisterNode',
            cloud__storage__pb2.RegisterNodeRequest.SerializeToString,
            cloud__storage__pb2.RegisterNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.NodeManagement/SendHeartbeat',
            cloud__storage__pb2.HeartbeatRequest.SerializeToString,
            cloud__storage__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyActive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.NodeManagement/NotifyActive',
            cloud__storage__pb2.ActiveNotificationRequest.SerializeToString,
            cloud__storage__pb2.ActiveNotificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.NodeManagement/GetNodeInfo',
            cloud__storage__pb2.NodeInfoRequest.SerializeToString,
            cloud__storage__pb2.NodeInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class FileManagementStub(object):
    """File management service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
                '/cloud_storage.FileManagement/UploadFile',
                request_serializer=cloud__storage__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.UploadFileResponse.FromString,
                )
        self.DownloadFile = channel.unary_unary(
                '/cloud_storage.FileManagement/DownloadFile',
                request_serializer=cloud__storage__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.DownloadFileResponse.FromString,
                )
        self.ListFiles = channel.unary_unary(
                '/cloud_storage.FileManagement/ListFiles',
                request_serializer=cloud__storage__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.ListFilesResponse.FromString,
                )
        self.NotifyUploadComplete = channel.unary_unary(
                '/cloud_storage.FileManagement/NotifyUploadComplete',
                request_serializer=cloud__storage__pb2.UploadCompleteRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.UploadCompleteResponse.FromString,
                )
        self.ReplicateFile = channel.unary_unary(
                '/cloud_storage.FileManagement/ReplicateFile',
                request_serializer=cloud__storage__pb2.ReplicateFileRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.ReplicateFileResponse.FromString,
                )


class FileManagementServicer(object):
    """File management service
    """

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyUploadComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=cloud__storage__pb2.UploadFileRequest.FromString,
                    response_serializer=cloud__storage__pb2.UploadFileResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=cloud__storage__pb2.DownloadFileRequest.FromString,
                    response_serializer=cloud__storage__pb2.DownloadFileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=cloud__storage__pb2.ListFilesRequest.FromString,
                    response_serializer=cloud__storage__pb2.ListFilesResponse.SerializeToString,
            ),
            'NotifyUploadComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyUploadComplete,
                    request_deserializer=cloud__storage__pb2.UploadCompleteRequest.FromString,
                    response_serializer=cloud__storage__pb2.UploadCompleteResponse.SerializeToString,
            ),
            'ReplicateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateFile,
                    request_deserializer=cloud__storage__pb2.ReplicateFileRequest.FromString,
                    response_serializer=cloud__storage__pb2.ReplicateFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud_storage.FileManagement', rpc_method_handlers)
    server.add_generic_handler(generic_handler)


 # This class is part of an EXPERIMENTAL API.
class FileManagement(object):
    """File management service
    """

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.FileManagement/UploadFile',
            cloud__storage__pb2.UploadFileRequest.SerializeToString,
            cloud__storage__pb2.UploadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.FileManagement/DownloadFile',
            cloud__storage__pb2.DownloadFileRequest.SerializeToString,
            cloud__storage__pb2.DownloadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.FileManagement/ListFiles',
            cloud__storage__pb2.ListFilesRequest.SerializeToString,
            cloud__storage__pb2.ListFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyUploadComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.FileManagement/NotifyUploadComplete',
            cloud__storage__pb2.UploadCompleteRequest.SerializeToString,
            cloud__storage__pb2.UploadCompleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.FileManagement/ReplicateFile',
            cloud__storage__pb2.ReplicateFileRequest.SerializeToString,
            cloud__storage__pb2.ReplicateFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class FileTransferStub(object):
    """File transfer service for node-to-node communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransferFile = channel.unary_unary(
                '/cloud_storage.FileTransfer/TransferFile',
                request_serializer=cloud__storage__pb2.TransferFileRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.TransferFileResponse.FromString,
                )
        self.TransferChunk = channel.unary_unary(
                '/cloud_storage.FileTransfer/TransferChunk',
                request_serializer=cloud__storage__pb2.TransferChunkRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.TransferChunkResponse.FromString,
                )
        self.ConnectNodes = channel.unary_unary(
                '/cloud_storage.FileTransfer/ConnectNodes',
                request_serializer=cloud__storage__pb2.ConnectNodesRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.ConnectNodesResponse.FromString,
                )


class FileTransferServicer(object):
    """File transfer service for node-to-node communication
    """

    def TransferFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransferFile': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferFile,
                    request_deserializer=cloud__storage__pb2.TransferFileRequest.FromString,
                    response_serializer=cloud__storage__pb2.TransferFileResponse.SerializeToString,
            ),
            'TransferChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferChunk,
                    request_deserializer=cloud__storage__pb2.TransferChunkRequest.FromString,
                    response_serializer=cloud__storage__pb2.TransferChunkResponse.SerializeToString,
            ),
            'ConnectNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectNodes,
                    request_deserializer=cloud__storage__pb2.ConnectNodesRequest.FromString,
                    response_serializer=cloud__storage__pb2.ConnectNodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud_storage.FileTransfer', rpc_method_handlers)
    server.add_generic_handler(generic_handler)


 # This class is part of an EXPERIMENTAL API.
class FileTransfer(object):
    """File transfer service for node-to-node communication
    """

    @staticmethod
    def TransferFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.FileTransfer/TransferFile',
            cloud__storage__pb2.TransferFileRequest.SerializeToString,
            cloud__storage__pb2.TransferFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TransferChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.FileTransfer/TransferChunk',
            cloud__storage__pb2.TransferChunkRequest.SerializeToString,
            cloud__storage__pb2.TransferChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud_storage.FileTransfer/ConnectNodes',
            cloud__storage__pb2.ConnectNodesRequest.SerializeToString,
            cloud__storage__pb2.ConnectNodesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
