# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloudsecurity_pb2 as cloudsecurity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloudsecurity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """=============================================================================
    UserService - Authentication service for user management
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.login = channel.unary_unary(
                '/cloud.UserService/login',
                request_serializer=cloudsecurity__pb2.LoginRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Signup = channel.unary_unary(
                '/cloud.UserService/Signup',
                request_serializer=cloudsecurity__pb2.SignupRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.SignupResponse.FromString,
                _registered_method=True)
        self.VerifyOTP = channel.unary_unary(
                '/cloud.UserService/VerifyOTP',
                request_serializer=cloudsecurity__pb2.VerifyOTPRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.VerifyOTPResponse.FromString,
                _registered_method=True)
        self.ResendOTP = channel.unary_unary(
                '/cloud.UserService/ResendOTP',
                request_serializer=cloudsecurity__pb2.ResendOTPRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.ResendOTPResponse.FromString,
                _registered_method=True)
        self.ForgotPassword = channel.unary_unary(
                '/cloud.UserService/ForgotPassword',
                request_serializer=cloudsecurity__pb2.ForgotPasswordRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.ForgotPasswordResponse.FromString,
                _registered_method=True)
        self.ResetPassword = channel.unary_unary(
                '/cloud.UserService/ResetPassword',
                request_serializer=cloudsecurity__pb2.ResetPasswordRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.ResetPasswordResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/cloud.UserService/ValidateToken',
                request_serializer=cloudsecurity__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/cloud.UserService/RefreshToken',
                request_serializer=cloudsecurity__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/cloud.UserService/Logout',
                request_serializer=cloudsecurity__pb2.LogoutRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.GetSessions = channel.unary_unary(
                '/cloud.UserService/GetSessions',
                request_serializer=cloudsecurity__pb2.GetSessionsRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.GetSessionsResponse.FromString,
                _registered_method=True)
        self.RevokeSession = channel.unary_unary(
                '/cloud.UserService/RevokeSession',
                request_serializer=cloudsecurity__pb2.RevokeSessionRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.RevokeSessionResponse.FromString,
                _registered_method=True)
        self.LogoutAll = channel.unary_unary(
                '/cloud.UserService/LogoutAll',
                request_serializer=cloudsecurity__pb2.LogoutAllRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.LogoutAllResponse.FromString,
                _registered_method=True)
        self.GetAuditLogs = channel.unary_unary(
                '/cloud.UserService/GetAuditLogs',
                request_serializer=cloudsecurity__pb2.GetAuditLogsRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.GetAuditLogsResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """=============================================================================
    UserService - Authentication service for user management
    =============================================================================
    """

    def login(self, request, context):
        """Login with username and password.
        On success, sends OTP to user's registered email.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Signup(self, request, context):
        """Register a new user account.
        Sends verification OTP to the provided email.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOTP(self, request, context):
        """Verify an OTP code (for signup verification or login 2FA).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResendOTP(self, request, context):
        """Resend OTP code to user's email.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgotPassword(self, request, context):
        """Request password reset - sends OTP to user's email.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPassword(self, request, context):
        """Reset password with OTP verification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Validate a JWT access token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Refresh access token using refresh token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout - revoke current session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessions(self, request, context):
        """Get all active sessions for current user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeSession(self, request, context):
        """Revoke a specific session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutAll(self, request, context):
        """Logout from all devices (revoke all sessions).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditLogs(self, request, context):
        """Get audit logs for the current user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=cloudsecurity__pb2.LoginRequest.FromString,
                    response_serializer=cloudsecurity__pb2.LoginResponse.SerializeToString,
            ),
            'Signup': grpc.unary_unary_rpc_method_handler(
                    servicer.Signup,
                    request_deserializer=cloudsecurity__pb2.SignupRequest.FromString,
                    response_serializer=cloudsecurity__pb2.SignupResponse.SerializeToString,
            ),
            'VerifyOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOTP,
                    request_deserializer=cloudsecurity__pb2.VerifyOTPRequest.FromString,
                    response_serializer=cloudsecurity__pb2.VerifyOTPResponse.SerializeToString,
            ),
            'ResendOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.ResendOTP,
                    request_deserializer=cloudsecurity__pb2.ResendOTPRequest.FromString,
                    response_serializer=cloudsecurity__pb2.ResendOTPResponse.SerializeToString,
            ),
            'ForgotPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ForgotPassword,
                    request_deserializer=cloudsecurity__pb2.ForgotPasswordRequest.FromString,
                    response_serializer=cloudsecurity__pb2.ForgotPasswordResponse.SerializeToString,
            ),
            'ResetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPassword,
                    request_deserializer=cloudsecurity__pb2.ResetPasswordRequest.FromString,
                    response_serializer=cloudsecurity__pb2.ResetPasswordResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=cloudsecurity__pb2.ValidateTokenRequest.FromString,
                    response_serializer=cloudsecurity__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=cloudsecurity__pb2.RefreshTokenRequest.FromString,
                    response_serializer=cloudsecurity__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=cloudsecurity__pb2.LogoutRequest.FromString,
                    response_serializer=cloudsecurity__pb2.LogoutResponse.SerializeToString,
            ),
            'GetSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessions,
                    request_deserializer=cloudsecurity__pb2.GetSessionsRequest.FromString,
                    response_serializer=cloudsecurity__pb2.GetSessionsResponse.SerializeToString,
            ),
            'RevokeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeSession,
                    request_deserializer=cloudsecurity__pb2.RevokeSessionRequest.FromString,
                    response_serializer=cloudsecurity__pb2.RevokeSessionResponse.SerializeToString,
            ),
            'LogoutAll': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutAll,
                    request_deserializer=cloudsecurity__pb2.LogoutAllRequest.FromString,
                    response_serializer=cloudsecurity__pb2.LogoutAllResponse.SerializeToString,
            ),
            'GetAuditLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditLogs,
                    request_deserializer=cloudsecurity__pb2.GetAuditLogsRequest.FromString,
                    response_serializer=cloudsecurity__pb2.GetAuditLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """=============================================================================
    UserService - Authentication service for user management
    =============================================================================
    """

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/login',
            cloudsecurity__pb2.LoginRequest.SerializeToString,
            cloudsecurity__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Signup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/Signup',
            cloudsecurity__pb2.SignupRequest.SerializeToString,
            cloudsecurity__pb2.SignupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/VerifyOTP',
            cloudsecurity__pb2.VerifyOTPRequest.SerializeToString,
            cloudsecurity__pb2.VerifyOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResendOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/ResendOTP',
            cloudsecurity__pb2.ResendOTPRequest.SerializeToString,
            cloudsecurity__pb2.ResendOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForgotPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/ForgotPassword',
            cloudsecurity__pb2.ForgotPasswordRequest.SerializeToString,
            cloudsecurity__pb2.ForgotPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/ResetPassword',
            cloudsecurity__pb2.ResetPasswordRequest.SerializeToString,
            cloudsecurity__pb2.ResetPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/ValidateToken',
            cloudsecurity__pb2.ValidateTokenRequest.SerializeToString,
            cloudsecurity__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/RefreshToken',
            cloudsecurity__pb2.RefreshTokenRequest.SerializeToString,
            cloudsecurity__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/Logout',
            cloudsecurity__pb2.LogoutRequest.SerializeToString,
            cloudsecurity__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/GetSessions',
            cloudsecurity__pb2.GetSessionsRequest.SerializeToString,
            cloudsecurity__pb2.GetSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/RevokeSession',
            cloudsecurity__pb2.RevokeSessionRequest.SerializeToString,
            cloudsecurity__pb2.RevokeSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogoutAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/LogoutAll',
            cloudsecurity__pb2.LogoutAllRequest.SerializeToString,
            cloudsecurity__pb2.LogoutAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/GetAuditLogs',
            cloudsecurity__pb2.GetAuditLogsRequest.SerializeToString,
            cloudsecurity__pb2.GetAuditLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
